// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pbl3_QLCF.Data;

#nullable disable

namespace pbl3_QLCF.Migrations
{
    [DbContext(typeof(Pbl3Context))]
    [Migration("20250609095512_FINAL")]
    partial class FINAL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pbl3_QLCF.Data.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KhuVucBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBan")
                        .HasName("PK__Ban__3520ED6C422C19FA");

                    b.ToTable("Ban", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ChiTietDonHang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaDH");

                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDh", "MaMon")
                        .HasName("PK__ChiTietD__B48034FBD6C60B2C");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.DonHang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaDH");

                    b.Property<string>("MaBan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("ThanhToan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ThoiGianDat")
                        .HasColumnType("datetime");

                    b.Property<int?>("TongTien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiDh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThaiDH");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__27258661D23B0614");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<int?>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("LoaiKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKH");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E13284CE0");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.NguoiDung", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("CaLamViec")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNv")
                        .HasName("PK__NguoiDun__2725D70A258C1FBD");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ThucDon", b =>
                {
                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GiaSp")
                        .HasColumnType("int")
                        .HasColumnName("GiaSP");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.HasKey("MaMon")
                        .HasName("PK__ThucDon__3A5B29A8C030D407");

                    b.ToTable("ThucDon", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaDH__09A971A2");

                    b.HasOne("pbl3_QLCF.Data.ThucDon", "MaMonNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaMon__0A9D95DB");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.DonHang", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.Ban", "MaBanNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaBan")
                        .HasConstraintName("FK__DonHang__MaBan__06CD04F7");

                    b.HasOne("pbl3_QLCF.Data.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DonHang__MaKH__04E4BC85");

                    b.HasOne("pbl3_QLCF.Data.NguoiDung", "MaNvNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__DonHang__MaNV__05D8E0BE");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.Ban", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ThucDon", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
