// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pbl3_QLCF.Data;

#nullable disable

namespace pbl3_QLCF.Migrations
{
    [DbContext(typeof(Pbl3Context))]
    partial class Pbl3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietKhuyenMai", b =>
                {
                    b.Property<string>("MaKm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKM");

                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKm", "MaMon")
                        .HasName("PK__ChiTietK__B4807D8F8F30185A");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietKhuyenMai", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KhuVucBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBan")
                        .HasName("PK__Ban__3520ED6C422C19FA");

                    b.ToTable("Ban", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.CaLamViec", b =>
                {
                    b.Property<string>("MaCaLamViec")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenCa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCaLamViec")
                        .HasName("PK__CaLamVie__E545F62584269E71");

                    b.ToTable("CaLamViec", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ChiTietDonHang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaDH");

                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDh", "MaMon")
                        .HasName("PK__ChiTietD__B48034FBD6C60B2C");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.CongThucMonAn", b =>
                {
                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNL");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("MaMon", "MaNl")
                        .HasName("PK__CongThuc__E82974DB2E3B7E9F");

                    b.HasIndex("MaNl");

                    b.ToTable("CongThucMonAn", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.DonHang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaDH");

                    b.Property<string>("MaBan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("ThanhToan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ThoiGianDat")
                        .HasColumnType("datetime");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.Property<string>("TrangThaiDh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThaiDH");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__27258661D23B0614");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.HoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaDh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaDH");

                    b.Property<DateOnly?>("Ngay")
                        .HasColumnType("date");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E040E95A9D");

                    b.HasIndex("MaDh");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<int?>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKH");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E13284CE0");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhoNguyenLieu", b =>
                {
                    b.Property<string>("MaNl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNL");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("Hsd")
                        .HasColumnType("date")
                        .HasColumnName("HSD");

                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Nsx")
                        .HasColumnType("date")
                        .HasColumnName("NSX");

                    b.Property<int?>("Sl")
                        .HasColumnType("int")
                        .HasColumnName("SL");

                    b.Property<string>("TenNl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNL");

                    b.HasKey("MaNl")
                        .HasName("PK__KhoNguye__2725D73C7BD649CA");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("KhoNguyenLieu", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhuyenMai", b =>
                {
                    b.Property<string>("MaKm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKM");

                    b.Property<string>("DkapDung")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DKApDung");

                    b.Property<double?>("GiaTriGiam")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayBd")
                        .HasColumnType("date")
                        .HasColumnName("NgayBD");

                    b.Property<DateOnly?>("NgayKt")
                        .HasColumnType("date")
                        .HasColumnName("NgayKT");

                    b.Property<string>("TenKm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKM");

                    b.HasKey("MaKm")
                        .HasName("PK__KhuyenMa__2725CF15FFCBA44B");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.NguoiDung", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("CaLamViec")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNv")
                        .HasName("PK__NguoiDun__2725D70A258C1FBD");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.NhaCungCap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__3A185DEB6CA7E147");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.PhanCongCaLamViec", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MaCaLamViec")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date");

                    b.HasKey("MaNv", "MaCaLamViec", "NgayLamViec")
                        .HasName("PK__PhanCong__D543FA9A746C1BC8");

                    b.HasIndex("MaCaLamViec");

                    b.ToTable("PhanCongCaLamViec", (string)null);
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ThucDon", b =>
                {
                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GiaSp")
                        .HasColumnType("int")
                        .HasColumnName("GiaSP");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TinhTrang")
                        .HasColumnType("bit");

                    b.HasKey("MaMon")
                        .HasName("PK__ThucDon__3A5B29A8C030D407");

                    b.ToTable("ThucDon", (string)null);
                });

            modelBuilder.Entity("ChiTietKhuyenMai", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.KhuyenMai", null)
                        .WithMany()
                        .HasForeignKey("MaKm")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietKhu__MaKM__74AE54BC");

                    b.HasOne("pbl3_QLCF.Data.ThucDon", null)
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietKh__MaMon__75A278F5");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaDH__09A971A2");

                    b.HasOne("pbl3_QLCF.Data.ThucDon", "MaMonNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaMon__0A9D95DB");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.CongThucMonAn", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.ThucDon", "MaMonNavigation")
                        .WithMany("CongThucMonAns")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("FK__CongThucM__MaMon__6EF57B66");

                    b.HasOne("pbl3_QLCF.Data.KhoNguyenLieu", "MaNlNavigation")
                        .WithMany("CongThucMonAns")
                        .HasForeignKey("MaNl")
                        .IsRequired()
                        .HasConstraintName("FK__CongThucMo__MaNL__6FE99F9F");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNlNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.DonHang", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.Ban", "MaBanNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaBan")
                        .HasConstraintName("FK__DonHang__MaBan__06CD04F7");

                    b.HasOne("pbl3_QLCF.Data.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DonHang__MaKH__04E4BC85");

                    b.HasOne("pbl3_QLCF.Data.NguoiDung", "MaNvNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__DonHang__MaNV__05D8E0BE");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.HoaDon", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.DonHang", "MaDhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDh")
                        .HasConstraintName("FK__HoaDon__MaDH__0D7A0286");

                    b.Navigation("MaDhNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhoNguyenLieu", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("KhoNguyenLieus")
                        .HasForeignKey("MaNhaCungCap")
                        .HasConstraintName("FK__KhoNguyen__MaNha__6A30C649");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.PhanCongCaLamViec", b =>
                {
                    b.HasOne("pbl3_QLCF.Data.CaLamViec", "MaCaLamViecNavigation")
                        .WithMany("PhanCongCaLamViecs")
                        .HasForeignKey("MaCaLamViec")
                        .IsRequired()
                        .HasConstraintName("FK__PhanCongC__MaCaL__00200768");

                    b.HasOne("pbl3_QLCF.Data.NguoiDung", "MaNvNavigation")
                        .WithMany("PhanCongCaLamViecs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__PhanCongCa__MaNV__7F2BE32F");

                    b.Navigation("MaCaLamViecNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.Ban", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.CaLamViec", b =>
                {
                    b.Navigation("PhanCongCaLamViecs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.KhoNguyenLieu", b =>
                {
                    b.Navigation("CongThucMonAns");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("PhanCongCaLamViecs");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.NhaCungCap", b =>
                {
                    b.Navigation("KhoNguyenLieus");
                });

            modelBuilder.Entity("pbl3_QLCF.Data.ThucDon", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("CongThucMonAns");
                });
#pragma warning restore 612, 618
        }
    }
}
